namespace Sepid.DeviceManagerTest.Common.Enum
{
    public enum AuthConfigType
    {
        EXT_FACE_ONLY = 11,    // 11
        EXT_FACE_FINGERPRINT = 12,
        EXT_FACE_PIN = 13,
        EXT_FACE_FINGERPRINT_OR_PIN = 14,
        EXT_FACE_FINGERPRINT_PIN = 15,
        EXT_FINGERPRINT_ONLY = 16,        // 16
        EXT_FINGERPRINT_FACE = 17,
        EXT_FINGERPRINT_PIN = 18,
        EXT_FINGERPRINT_FACE_OR_PIN = 19,
        EXT_FINGERPRINT_FACE_PIN = 20,
        EXT_CARD_ONLY = 21,     // 21
        EXT_CARD_FACE = 22,
        EXT_CARD_FINGERPRINT = 23,
        EXT_CARD_PIN = 24,
        EXT_CARD_FACE_OR_FINGERPRINT = 25,
        EXT_CARD_FACE_OR_PIN = 26,
        EXT_CARD_FINGERPRINT_OR_PIN = 27,
        EXT_CARD_FACE_OR_FINGERPRINT_OR_PIN = 28,
        EXT_CARD_FACE_FINGERPRINT = 29,
        EXT_CARD_FACE_PIN = 30,
        EXT_CARD_FINGERPRINT_FACE = 31,
        EXT_CARD_FINGERPRINT_PIN = 32,
        EXT_CARD_FACE_OR_FINGERPRINT_PIN = 33,
        EXT_CARD_FACE_FINGERPRINT_OR_PIN = 34,
        EXT_CARD_FINGERPRINT_FACE_OR_PIN = 35,
        EXT_ID_FACE = 36,     // 36
        EXT_ID_FINGERPRINT = 37,
        EXT_ID_PIN = 38,
        EXT_ID_FACE_OR_FINGERPRINT = 39,
        EXT_ID_FACE_OR_PIN = 40,
        EXT_ID_FINGERPRINT_OR_PIN = 41,
        EXT_ID_FACE_OR_FINGERPRINT_OR_PIN = 42,
        EXT_ID_FACE_FINGERPRINT = 43,
        EXT_ID_FACE_PIN = 44,
        EXT_ID_FINGERPRINT_FACE = 45,
        EXT_ID_FINGERPRINT_PIN = 46,
        EXT_ID_FACE_OR_FINGERPRINT_PIN = 47,
        EXT_ID_FACE_FINGERPRINT_OR_PIN = 48,
        EXT_ID_FINGERPRINT_FACE_OR_PIN = 49,

    }
}